const HINTS = [
    { solution: "Cerveza", l1: "Bebida", l2: "Fría", l3: "Noche" },
    { solution: "Discoteca", l1: "Fiesta", l2: "Música alta", l3: "Noche" },
    { solution: "Hotel", l1: "Viaje", l2: "Cama", l3: "Habitación" },
    { solution: "Whatsapp", l1: "Mensajes", l2: "Chats", l3: "Móvil" },
    { solution: "Sofá", l1: "Casa", l2: "Descanso", l3: "Salón" },
    { solution: "Ducha", l1: "Agua", l2: "Baño", l3: "Caliente" },
    { solution: "Cama", l1: "Dormir", l2: "Noche", l3: "Descanso" },
    { solution: "Besos", l1: "Cariño", l2: "Labios", l3: "Contacto" },
    { solution: "Copas", l1: "Alcohol", l2: "Noche", l3: "Bar" },
    { solution: "Resaca", l1: "Mañana", l2: "Dolor de cabeza", l3: "Después" },

    { solution: "Piscina", l1: "Agua", l2: "Verano", l3: "Chapuzón" },
    { solution: "Fiesta sorpresa", l1: "Evento", l2: "Secreto", l3: "Amigos" },
    { solution: "Selfie", l1: "Foto", l2: "Móvil", l3: "Cara" },
    { solution: "Cine", l1: "Pantalla", l2: "Película", l3: "Butaca" },
    { solution: "Manta", l1: "Frío", l2: "Sofá", l3: "Taparse" },
    { solution: "Palomitas", l1: "Comida", l2: "Cine", l3: "Snack" },
    { solution: "Spotify", l1: "Música", l2: "Auriculares", l3: "App" },
    { solution: "TikTok", l1: "Vídeos", l2: "Scroll", l3: "Red social" },
    { solution: "Helado", l1: "Frío", l2: "Dulce", l3: "Verano" },
    { solution: "Barbacoa", l1: "Comida", l2: "Carne", l3: "Amigos" },

    { solution: "Miradas", l1: "Gestos", l2: "Silencio", l3: "Tensión" },
    { solution: "Cita", l1: "Dos personas", l2: "Nervios", l3: "Encuentro" },
    { solution: "After", l1: "Noche", l2: "Tarde", l3: "Continuar" },
    { solution: "Mensaje borracho", l1: "Móvil", l2: "Noche", l3: "Error" },
    { solution: "Ex", l1: "Pasado", l2: "Recuerdos", l3: "Peligro" },
    { solution: "Tontear", l1: "Juego", l2: "Indirectas", l3: "Risas" },
    { solution: "Calor", l1: "Sensación", l2: "Verano", l3: "Sube" },
    { solution: "Mirador", l1: "Lugar", l2: "Vistas", l3: "Romántico" },
    { solution: "Sudadera", l1: "Ropa", l2: "Grande", l3: "Prestada" },

    { solution: "Vacaciones", l1: "Tiempo libre", l2: "Viaje", l3: "Descanso" },
    { solution: "Chiringuito", l1: "Playa", l2: "Bebidas", l3: "Verano" },
    { solution: "Risa tonta", l1: "Momento", l2: "Sin motivo", l3: "Nervios" },
    { solution: "Indirecta", l1: "Mensaje", l2: "No directo", l3: "Intención" },
    { solution: "Noche loca", l1: "Fiesta", l2: "Improvisar", l3: "Recuerdos" },
    { solution: "Abrazo", l1: "Contacto", l2: "Cercanía", l3: "Calor" },
    { solution: "Mirada incómoda", l1: "Silencio", l2: "Tensión", l3: "Momento" },
    { solution: "Confesión", l1: "Verdad", l2: "Valor", l3: "Momento" },
    { solution: "Story", l1: "Instagram", l2: "24 horas", l3: "Subir" },
    { solution: "Like", l1: "Red social", l2: "Corazón", l3: "Interacción" },

    { solution: "Casa vacía", l1: "Silencio", l2: "Oportunidad", l3: "Momento" },
    { solution: "Nervios", l1: "Sensación", l2: "Barriga", l3: "Antes" },
    { solution: "Guiño", l1: "Ojo", l2: "Señal", l3: "Mensaje" },
    { solution: "Fiesta universitaria", l1: "Jóvenes", l2: "Alcohol", l3: "Noche" },
    { solution: "Mirarse demasiado", l1: "Ojos", l2: "Tiempo", l3: "Algo pasa" },
    { solution: "Playlist nocturna", l1: "Música", l2: "Mood", l3: "Noche" },
    { solution: "Mensaje a las 3 AM", l1: "Hora rara", l2: "Tentación", l3: "Peligro" },
    { solution: "Foto provocadora", l1: "Imagen", l2: "Intención", l3: "Reacción" },
    { solution: "Reto", l1: "Juego", l2: "Valor", l3: "Grupo" },
    { solution: "Verdad o reto", l1: "Juego", l2: "Confesiones", l3: "Risas" },

    { solution: "Mirada cómplice", l1: "Secreto", l2: "Dos personas", l3: "Conexión" },
    { solution: "Noche de verano", l1: "Calor", l2: "Larga", l3: "Magia" },
    { solution: "Química", l1: "Sensación", l2: "Difícil de explicar", l3: "Entre dos" },
    { solution: "Tensión", l1: "Ambiente", l2: "Silencio", l3: "Se nota" },
    { solution: "Mensaje eliminado", l1: "Chat", l2: "Arrepentimiento", l3: "Tarde" },
    { solution: "Foto guardada", l1: "Galería", l2: "Secreto", l3: "Privado" },
    { solution: "Plan improvisado", l1: "Última hora", l2: "Noche", l3: "Sin pensar" },
    { solution: "Mirar el móvil sonriendo", l1: "Mensaje", l2: "Persona", l3: "Interés" },
    { solution: "Cerveza de más", l1: "Alcohol", l2: "Valentía", l3: "Consecuencias" },
    { solution: "Silencio incómodo", l1: "Momento", l2: "Tensión", l3: "Ambiente" },

    { solution: "Llaves", l1: "Objeto", l2: "Siempre se pierden", l3: "Necesarias" },
    { solution: "Móvil", l1: "Tecnología", l2: "Siempre encima", l3: "Pantalla" },
    { solution: "Carretera", l1: "Viaje", l2: "Asfalto", l3: "Conduce" },
    { solution: "Cargador", l1: "Energía", l2: "Se presta", l3: "Nunca aparece" },
    { solution: "Zapatillas", l1: "Ropa", l2: "Cómodas", l3: "Uso diario" },
    { solution: "Mochila", l1: "Objeto", l2: "Llevar cosas", l3: "Espalda" },
    { solution: "Clase", l1: "Rutina", l2: "Horario", l3: "Aprender" },
    { solution: "Examen", l1: "Estrés", l2: "Estudiar", l3: "Fecha" },
    { solution: "Despertador", l1: "Mañana", l2: "Sonido", l3: "Odio" },
    { solution: "Cola", l1: "Espera", l2: "Gente", l3: "Paciencia" },

    { solution: "Semáforo", l1: "Ciudad", l2: "Colores", l3: "Parar" },
    { solution: "Café", l1: "Bebida", l2: "Mañana", l3: "Despertar" },
    { solution: "Paraguas", l1: "Objeto", l2: "Lluvia", l3: "Olvidado" },
    { solution: "Ascensor", l1: "Edificio", l2: "Subir y bajar", l3: "Botones" },
    { solution: "Factura", l1: "Papel", l2: "Pago", l3: "Molesta" },
    { solution: "Calendario", l1: "Tiempo", l2: "Fechas", l3: "Organizar" },
    { solution: "Fila del súper", l1: "Compra", l2: "Lenta", l3: "Esperar" },
    { solution: "Auriculares", l1: "Música", l2: "Cables", l3: "Uno se pierde" },
    { solution: "Notificación", l1: "Móvil", l2: "Sonido", l3: "Atención" },
    { solution: "Contraseña", l1: "Seguridad", l2: "Difícil", l3: "Se olvida" },

    { solution: "Bolígrafo", l1: "Escribir", l2: "Clase", l3: "Desaparece" },
    { solution: "Agenda", l1: "Organización", l2: "Apuntar", l3: "Plan" },
    { solution: "Espera", l1: "Tiempo", l2: "Aburrimiento", l3: "Paciencia" },
    { solution: "Puerta", l1: "Objeto", l2: "Abrir o cerrar", l3: "Paso" },
    { solution: "Ventana", l1: "Casa", l2: "Luz", l3: "Aire" },
    { solution: "Vecino", l1: "Persona", l2: "Cerca", l3: "Ruido" },
    { solution: "Tráfico", l1: "Coches", l2: "Ciudad", l3: "Estrés" },
    { solution: "Horario", l1: "Tiempo", l2: "Rutina", l3: "Orden" },
    { solution: "Mensaje leído", l1: "Chat", l2: "Silencio", l3: "Duda" },
    { solution: "Plan", l1: "Idea", l2: "Personas", l3: "Organizar" },

    { solution: "Llamada perdida", l1: "Móvil", l2: "Pantalla", l3: "Intriga" },
    { solution: "Reunión", l1: "Personas", l2: "Hablar", l3: "Tiempo" },
    { solution: "Fila del baño", l1: "Lugar", l2: "Prisa", l3: "Esperar" },
    { solution: "Cambio suelto", l1: "Dinero", l2: "Bolsillo", l3: "Ruido" },
    { solution: "Ticket", l1: "Papel", l2: "Compra", l3: "Se pierde" },
    { solution: "Mapa", l1: "Ubicación", l2: "Buscar", l3: "Orientarse" },
    { solution: "Silencio", l1: "Ambiente", l2: "Calma", l3: "Raro" },
    { solution: "Reloj", l1: "Tiempo", l2: "Mirar", l3: "Tarde" },
    { solution: "Plan cancelado", l1: "Aviso", l2: "Última hora", l3: "Fastidio" },

    // ===== DEPORTES (10) =====
    { solution: "Fútbol", l1: "Deporte", l2: "Balón", l3: "Equipo" },
    { solution: "Baloncesto", l1: "Canasta", l2: "Equipo", l3: "Puntos" },
    { solution: "Tenis", l1: "Raqueta", l2: "Individual", l3: "Red" },
    { solution: "Natación", l1: "Agua", l2: "Piscina", l3: "Resistencia" },
    { solution: "Ciclismo", l1: "Bicicleta", l2: "Ruta", l3: "Piernas" },
    { solution: "Boxeo", l1: "Combate", l2: "Guantes", l3: "Ring" },
    { solution: "Running", l1: "Correr", l2: "Zapatillas", l3: "Resistencia" },
    { solution: "Pádel", l1: "Parejas", l2: "Pared", l3: "Raqueta" },
    { solution: "Crossfit", l1: "Alta intensidad", l2: "Circuito", l3: "Cansancio" },
    { solution: "Surf", l1: "Mar", l2: "Tabla", l3: "Olas" },

    // ===== FAMOSOS (10) =====
    { solution: "Cristiano Ronaldo", l1: "Fútbol", l2: "Portugués", l3: "Goles" },
    { solution: "Ibai", l1: "Streamer", l2: "Eventos", l3: "Twitch" },
    { solution: "Bad Bunny", l1: "Cantante", l2: "Reguetón", l3: "Puerto Rico" },
    { solution: "Aitana", l1: "Cantante", l2: "Pop", l3: "España" },
    { solution: "TheGrefg", l1: "Youtuber", l2: "Gaming", l3: "Directos" },
    { solution: "Karol G", l1: "Música", l2: "Colombia", l3: "Éxitos" },
    { solution: "Duki", l1: "Trap", l2: "Argentina", l3: "Conciertos" },

    // ===== GIMNASIO (10) =====
    { solution: "Press banca", l1: "Pecho", l2: "Barra", l3: "Fuerza" },
    { solution: "Sentadilla", l1: "Piernas", l2: "Peso", l3: "Ejercicio" },
    { solution: "Peso muerto", l1: "Espalda", l2: "Barra", l3: "Técnica" },
    { solution: "Mancuernas", l1: "Material", l2: "Brazos", l3: "Pesos" },
    { solution: "Proteína", l1: "Suplemento", l2: "Batido", l3: "Recuperación" },
    { solution: "Series", l1: "Entreno", l2: "Repeticiones", l3: "Descanso" },
    { solution: "Cardio", l1: "Resistencia", l2: "Correr", l3: "Sudor" },
    { solution: "Monitor", l1: "Gimnasio", l2: "Ayuda", l3: "Rutina" },
    { solution: "Agujetas", l1: "Dolor", l2: "Después", l3: "Entreno" },
    { solution: "Máquinas", l1: "Gimnasio", l2: "Pesos", l3: "Rutina" },

    // ===== TEMÁTICA LIBRE: VIDA COTIDIANA (10) =====
    { solution: "Móvil", l1: "Tecnología", l2: "Pantalla", l3: "Diario" },
    { solution: "Coche", l1: "Transporte", l2: "Conducir", l3: "Viaje" },
    { solution: "Trabajo", l1: "Rutina", l2: "Horario", l3: "Responsabilidad" },
    { solution: "Fiesta", l1: "Noche", l2: "Amigos", l3: "Música" },
    { solution: "Vacaciones", l1: "Descanso", l2: "Viaje", l3: "Tiempo libre" },
    { solution: "Casa", l1: "Lugar", l2: "Descanso", l3: "Hogar" },
    { solution: "Cena", l1: "Comida", l2: "Noche", l3: "Mesa" },
    { solution: "Mensaje", l1: "Comunicación", l2: "Móvil", l3: "Texto" },
    { solution: "Plan", l1: "Idea", l2: "Personas", l3: "Organizar" },
    { solution: "Fin de semana", l1: "Tiempo libre", l2: "Descanso", l3: "Esperado" },
    { solution: "Spoiler", l1: "Información", l2: "Película", l3: "Arruina" },
    { solution: "Drama", l1: "Exageración", l2: "Reacción", l3: "De más" },
    { solution: "Pringado", l1: "Persona", l2: "Mala suerte", l3: "Siempre cae" },
    { solution: "PS5", l1: "Para Jugar", l2: "Mando", l3: "Tele" },
    { solution: "Cartera", l1: "Objeto", l2: "Dinero", l3: "Bolsillo" },
    { solution: "Llaves", l1: "Objeto", l2: "Abrir", l3: "Se pierden" },
    { solution: "Gafas", l1: "Objeto", l2: "Ver", l3: "Cristales" },
    { solution: "Paraguas", l1: "Objeto", l2: "Lluvia", l3: "Olvidado" },
    { solution: "Zapatillas", l1: "Objeto", l2: "Calzado", l3: "Cómodas" },
    { solution: "Mochila", l1: "Objeto", l2: "Espalda", l3: "Cremallera" },
    { solution: "Botella", l1: "Objeto", l2: "Agua", l3: "Tapón" },
    { solution: "Taza", l1: "Objeto", l2: "Beber", l3: "Asa" },
    { solution: "Cuchara", l1: "Objeto", l2: "Comer", l3: "Metal" },
    { solution: "Plato", l1: "Objeto", l2: "Comida", l3: "Redondo" },
    // ===== EXTRA VIDA REAL (20) =====
    { solution: "Lavadora", l1: "Electrodoméstico", l2: "Ropa", l3: "Girar" },
    { solution: "Congelador", l1: "Electrodoméstico", l2: "Hielo", l3: "Muy frío" },
    { solution: "Escoba", l1: "Objeto", l2: "Limpiar", l3: "Suelo" },
    { solution: "Fregona", l1: "Objeto", l2: "Agua", l3: "Limpieza" },
    { solution: "Tendedero", l1: "Objeto", l2: "Ropa", l3: "Secar" },

    { solution: "Panadería", l1: "Lugar", l2: "Pan", l3: "Olor" },
    { solution: "Farmacia", l1: "Lugar", l2: "Medicinas", l3: "Cruz verde" },
    { solution: "Gasolinera", l1: "Lugar", l2: "Coche", l3: "Repostar" },
    { solution: "Biblioteca", l1: "Lugar", l2: "Libros", l3: "Silencio" },
    { solution: "Gimnasio", l1: "Lugar", l2: "Pesas", l3: "Sudor" },

    { solution: "Camarero", l1: "Persona", l2: "Bar", l3: "Pedidos" },
    { solution: "Profesor", l1: "Persona", l2: "Clase", l3: "Explicar" },
    { solution: "Repartidor", l1: "Persona", l2: "Paquetes", l3: "Entrega" },
    { solution: "Vecina", l1: "Persona", l2: "Edificio", l3: "Cerca" },

    { solution: "Hamburguesa", l1: "Comida", l2: "Carne", l3: "Pan" },
    { solution: "Pizza", l1: "Comida", l2: "Horno", l3: "Porciones" },

    { solution: "Canario", l1: "Animal", l2: "Pájaro", l3: "Canta" },
    { solution: "Pez", l1: "Animal", l2: "Agua", l3: "Aletas" },

    { solution: "Maceta", l1: "Objeto", l2: "Planta", l3: "Tierra" },
    // ===== PERSONAJES CONOCIDOS (10) =====
    { solution: "Trump", l1: "Política", l2: "Estados Unidos", l3: "Presidente" },
    { solution: "Sánchez", l1: "Política", l2: "España", l3: "Presidente" },
    { solution: "Messi", l1: "Deporte", l2: "Fútbol", l3: "Balón" },
    { solution: "Rosalía", l1: "Música", l2: "España", l3: "Cantante" },
    { solution: "Elon", l1: "Tecnología", l2: "Empresas", l3: "Espacio" },
    { solution: "Shakira", l1: "Música", l2: "Colombia", l3: "Bailar" },
    { solution: "Piqué", l1: "Deporte", l2: "Fútbol", l3: "Defensa" },

    // ===== NUEVAS PALABRAS (Añadidas por IA) =====
    { solution: "Tequila", l1: "Bebida", l2: "Chupito", l3: "Sal y limón" },
    { solution: "Vino", l1: "Bebida", l2: "Uva", l3: "Tinto o blanco" },
    { solution: "Croquetas", l1: "Comida", l2: "Caseras", l3: "Cremosas" },
    { solution: "Tapas", l1: "Comida", l2: "Pequeñas", l3: "Bar" },
    { solution: "Paella", l1: "Comida", l2: "Arroz", l3: "Domingo" },

    { solution: "Netflix", l1: "App", l2: "Series", l3: "Manta y peli" },
    { solution: "Bizum", l1: "App", l2: "Dinero", l3: "Amigos" },
    { solution: "Instagram", l1: "App", l2: "Fotos", l3: "Stories" },
    { solution: "Twitter", l1: "App", l2: "Opinión", l3: "280 caracteres" },
    { solution: "Podcast", l1: "Audio", l2: "Programa", l3: "Escuchar" },

    { solution: "Playa", l1: "Lugar", l2: "Arena", l3: "Verano" },
    { solution: "Montaña", l1: "Lugar", l2: "Senderismo", l3: "Naturaleza" },
    { solution: "Aeropuerto", l1: "Lugar", l2: "Aviones", l3: "Viaje" },
    { solution: "Museo", l1: "Lugar", l2: "Arte", l3: "Silencio" },
    { solution: "Concierto", l1: "Evento", l2: "Música", l3: "Directo" },

    { solution: "Gafas de sol", l1: "Objeto", l2: "Verano", l3: "Proteger" },
    { solution: "Portátil", l1: "Objeto", l2: "Trabajo", l3: "Teclado" },
    { solution: "Batería externa", l1: "Objeto", l2: "Móvil", l3: "Cargar" },
    { solution: "Parada de bus", l1: "Lugar", l2: "Espera", l3: "Transporte" },
    { solution: "Supermercado", l1: "Lugar", l2: "Compra", l3: "Comida" },

    { solution: "Dejavú", l1: "Sensación", l2: "Repetido", l3: "Momento" },
    { solution: "Vergüenza ajena", l1: "Sensación", l2: "Incómodo", l3: "Por otro" },
    { solution: "Crush", l1: "Persona", l2: "Secreto", l3: "Te gusta" },
    { solution: "Ghosting", l1: "Acción", l2: "Desaparecer", l3: "Sin responder" },
    { solution: "Salseo", l1: "Cotilleo", l2: "Drama", l3: "Interés" },

    { solution: "Mando", l1: "Objeto", l2: "Jugar", l3: "Consola" },
    { solution: "Teclado y ratón", l1: "Objeto", l2: "PC", l3: "Jugar" },
    { solution: "Partida online", l1: "Actividad", l2: "Competir", l3: "Internet" },
    { solution: "Lag", l1: "Problema", l2: "Conexión", l3: "Lento" },
    { solution: "Skin", l1: "Objeto", l2: "Aspecto", l3: "Personaje" },

    // ===== NUEVAS PALABRAS 2 (Añadidas por IA) =====
    { solution: "La Casa de Papel", l1: "Serie", l2: "Atraco", l3: "Máscara de Dalí" },
    { solution: "Juego de Tronos", l1: "Serie", l2: "Dragones", l3: "Trono de Hierro" },
    { solution: "Harry Potter", l1: "Película", l2: "Magia", l3: "Cicatriz" },
    { solution: "Star Wars", l1: "Película", l2: "Galaxia", l3: "Espada láser" },
    { solution: "El Señor de los Anillos", l1: "Película", l2: "Anillo", l3: "Comunidad" },
    { solution: "Mando a distancia", l1: "Objeto", l2: "Sofá", l3: "Cambiar de canal" },
    { solution: "Buzón", l1: "Objeto", l2: "Cartas", l3: "Correo" },
    { solution: "Enchufe", l1: "Objeto", l2: "Pared", l3: "Electricidad" },
    { solution: "Bombilla", l1: "Objeto", l2: "Luz", l3: "Se funde" },
    { solution: "Ticket de compra", l1: "Papel", l2: "Devolución", l3: "Supermercado" },
    { solution: "Alarma", l1: "Sonido", l2: "Despertar", l3: "Urgencia" },
    { solution: "Propina", l1: "Dinero", l2: "Agradecimiento", l3: "Camarero" },
    { solution: "DNI", l1: "Documento", l2: "Identidad", l3: "Foto" },
    { solution: "Wi-Fi", l1: "Conexión", l2: "Contraseña", l3: "Internet" },
    { solution: "Ascensor", l1: "Máquina", l2: "Subir", l3: "Botones" },
    { solution: "Correo electrónico", l1: "Mensaje", l2: "Trabajo", l3: "Asunto" },
    { solution: "Reunión de trabajo", l1: "Evento", l2: "Oficina", l3: "Hablar" },
    { solution: "Fecha de entrega", l1: "Límite", l2: "Estrés", l3: "Proyecto" },
    { solution: "Compañero de piso", l1: "Persona", l2: "Casa", l3: "Convivencia" },
    { solution: "Apuntes", l1: "Papel", l2: "Estudiar", l3: "Clase" },
    { solution: "Perro", l1: "Animal", l2: "Mascota", l3: "Ladrar" },
    { solution: "Gato", l1: "Animal", l2: "Mascota", l3: "Maullar" },
    { solution: "Lluvia", l1: "Clima", l2: "Agua", l3: "Paraguas" },
    { solution: "Nieve", l1: "Clima", l2: "Frío", l3: "Blanco" },
    { solution: "Río", l1: "Naturaleza", l2: "Agua", l3: "Corriente" },
    { solution: "Tatuaje", l1: "Piel", l2: "Tinta", l3: "Permanente" },
    { solution: "Cicatriz", l1: "Piel", l2: "Herida", l3: "Marca" },
    { solution: "Fiebre", l1: "Síntoma", l2: "Enfermedad", l3: "Temperatura" },
    { solution: "Dolor de cabeza", l1: "Sensación", l2: "Molestia", l3: "Pastilla" },
    { solution: "Vitamina", l1: "Suplemento", l2: "Salud", l3: "Naranja" },
    { solution: "Ironía", l1: "Lenguaje", l2: "Sarcasmo", l3: "No literal" },
    { solution: "Destino", l1: "Concepto", l2: "Futuro", l3: "Escrito" },
    { solution: "Casualidad", l1: "Concepto", l2: "Azar", l3: "Sin planear" },
    { solution: "Rumor", l1: "Información", l2: "No confirmado", l3: "Cotilleo" },
    { solution: "Secreto", l1: "Información", l2: "Oculto", l3: "Confianza" },
    { solution: "Cocinar", l1: "Actividad", l2: "Comida", l3: "Receta" },
    { solution: "Leer", l1: "Actividad", l2: "Libro", l3: "Imaginación" },
    { solution: "Viajar", l1: "Actividad", l2: "Mundo", l3: "Experiencias" },
    { solution: "Bailar", l1: "Actividad", l2: "Música", l3: "Ritmo" },
    { solution: "Dibujar", l1: "Actividad", l2: "Arte", l3: "Lápiz" }
];