const HINTS = [
    { solution: "Cerveza", l1: "Bebida", l2: "Fría", l3: "Noche" },
    { solution: "Discoteca", l1: "Fiesta", l2: "Música alta", l3: "Noche" },
    { solution: "Hotel", l1: "Viaje", l2: "Cama", l3: "Habitación" },
    { solution: "Whatsapp", l1: "Mensajes", l2: "Chats", l3: "Móvil" },
    { solution: "Sofá", l1: "Casa", l2: "Descanso", l3: "Salón" },
    { solution: "Ducha", l1: "Agua", l2: "Baño", l3: "Caliente" },
    { solution: "Cama", l1: "Dormir", l2: "Noche", l3: "Descanso" },
    { solution: "Besos", l1: "Cariño", l2: "Labios", l3: "Contacto" },
    { solution: "Copas", l1: "Alcohol", l2: "Noche", l3: "Bar" },
    { solution: "Resaca", l1: "Mañana", l2: "Dolor de cabeza", l3: "Después" },

    { solution: "Piscina", l1: "Agua", l2: "Verano", l3: "Chapuzón" },
    { solution: "Fiesta sorpresa", l1: "Evento", l2: "Secreto", l3: "Amigos" },
    { solution: "Selfie", l1: "Foto", l2: "Móvil", l3: "Cara" },
    { solution: "Cine", l1: "Pantalla", l2: "Película", l3: "Butaca" },
    { solution: "Manta", l1: "Frío", l2: "Sofá", l3: "Taparse" },
    { solution: "Palomitas", l1: "Comida", l2: "Cine", l3: "Snack" },
    { solution: "Spotify", l1: "Música", l2: "Auriculares", l3: "App" },
    { solution: "TikTok", l1: "Vídeos", l2: "Scroll", l3: "Red social" },
    { solution: "Helado", l1: "Frío", l2: "Dulce", l3: "Verano" },
    { solution: "Barbacoa", l1: "Comida", l2: "Carne", l3: "Amigos" },

    { solution: "Miradas", l1: "Gestos", l2: "Silencio", l3: "Tensión" },
    { solution: "Cita", l1: "Dos personas", l2: "Nervios", l3: "Encuentro" },
    { solution: "After", l1: "Noche", l2: "Tarde", l3: "Continuar" },
    { solution: "Mensaje borracho", l1: "Móvil", l2: "Noche", l3: "Error" },
    { solution: "Ex", l1: "Pasado", l2: "Recuerdos", l3: "Peligro" },
    { solution: "Tontear", l1: "Juego", l2: "Indirectas", l3: "Risas" },
    { solution: "Baile pegado", l1: "Música", l2: "Cerca", l3: "Discoteca" },
    { solution: "Calor", l1: "Sensación", l2: "Verano", l3: "Sube" },
    { solution: "Mirador", l1: "Lugar", l2: "Vistas", l3: "Romántico" },
    { solution: "Sudadera", l1: "Ropa", l2: "Grande", l3: "Prestada" },

    { solution: "Vacaciones", l1: "Tiempo libre", l2: "Viaje", l3: "Descanso" },
    { solution: "Chiringuito", l1: "Playa", l2: "Bebidas", l3: "Verano" },
    { solution: "Risa tonta", l1: "Momento", l2: "Sin motivo", l3: "Nervios" },
    { solution: "Indirecta", l1: "Mensaje", l2: "No directo", l3: "Intención" },
    { solution: "Noche loca", l1: "Fiesta", l2: "Improvisar", l3: "Recuerdos" },
    { solution: "Abrazo", l1: "Contacto", l2: "Cercanía", l3: "Calor" },
    { solution: "Mirada incómoda", l1: "Silencio", l2: "Tensión", l3: "Momento" },
    { solution: "Confesión", l1: "Verdad", l2: "Valor", l3: "Momento" },
    { solution: "Story", l1: "Instagram", l2: "24 horas", l3: "Subir" },
    { solution: "Like", l1: "Red social", l2: "Corazón", l3: "Interacción" },

    { solution: "Casa vacía", l1: "Silencio", l2: "Oportunidad", l3: "Momento" },
    { solution: "Nervios", l1: "Sensación", l2: "Barriga", l3: "Antes" },
    { solution: "Guiño", l1: "Ojo", l2: "Señal", l3: "Mensaje" },
    { solution: "Fiesta universitaria", l1: "Jóvenes", l2: "Alcohol", l3: "Noche" },
    { solution: "Mirarse demasiado", l1: "Ojos", l2: "Tiempo", l3: "Algo pasa" },
    { solution: "Playlist nocturna", l1: "Música", l2: "Mood", l3: "Noche" },
    { solution: "Mensaje a las 3 AM", l1: "Hora rara", l2: "Tentación", l3: "Peligro" },
    { solution: "Foto provocadora", l1: "Imagen", l2: "Intención", l3: "Reacción" },
    { solution: "Reto", l1: "Juego", l2: "Valor", l3: "Grupo" },
    { solution: "Verdad o reto", l1: "Juego", l2: "Confesiones", l3: "Risas" },

    { solution: "Mirada cómplice", l1: "Secreto", l2: "Dos personas", l3: "Conexión" },
    { solution: "Noche de verano", l1: "Calor", l2: "Larga", l3: "Magia" },
    { solution: "Química", l1: "Sensación", l2: "Difícil de explicar", l3: "Entre dos" },
    { solution: "Tensión", l1: "Ambiente", l2: "Silencio", l3: "Se nota" },
    { solution: "Mensaje eliminado", l1: "Chat", l2: "Arrepentimiento", l3: "Tarde" },
    { solution: "Foto guardada", l1: "Galería", l2: "Secreto", l3: "Privado" },
    { solution: "Plan improvisado", l1: "Última hora", l2: "Noche", l3: "Sin pensar" },
    { solution: "Mirar el móvil sonriendo", l1: "Mensaje", l2: "Persona", l3: "Interés" },
    { solution: "Cerveza de más", l1: "Alcohol", l2: "Valentía", l3: "Consecuencias" },
    { solution: "Silencio incómodo", l1: "Momento", l2: "Tensión", l3: "Ambiente" },

    { solution: "Llaves", l1: "Objeto", l2: "Siempre se pierden", l3: "Necesarias" },
    { solution: "Móvil", l1: "Tecnología", l2: "Siempre encima", l3: "Pantalla" },
    { solution: "Carretera", l1: "Viaje", l2: "Asfalto", l3: "Conduce" },
    { solution: "Cargador", l1: "Energía", l2: "Se presta", l3: "Nunca aparece" },
    { solution: "Zapatillas", l1: "Ropa", l2: "Cómodas", l3: "Uso diario" },
    { solution: "Mochila", l1: "Objeto", l2: "Llevar cosas", l3: "Espalda" },
    { solution: "Clase", l1: "Rutina", l2: "Horario", l3: "Aprender" },
    { solution: "Examen", l1: "Estrés", l2: "Estudiar", l3: "Fecha" },
    { solution: "Despertador", l1: "Mañana", l2: "Sonido", l3: "Odio" },
    { solution: "Cola", l1: "Espera", l2: "Gente", l3: "Paciencia" },

    { solution: "Semáforo", l1: "Ciudad", l2: "Colores", l3: "Parar" },
    { solution: "Café", l1: "Bebida", l2: "Mañana", l3: "Despertar" },
    { solution: "Paraguas", l1: "Objeto", l2: "Lluvia", l3: "Olvidado" },
    { solution: "Ascensor", l1: "Edificio", l2: "Subir y bajar", l3: "Botones" },
    { solution: "Factura", l1: "Papel", l2: "Pago", l3: "Molesta" },
    { solution: "Calendario", l1: "Tiempo", l2: "Fechas", l3: "Organizar" },
    { solution: "Fila del súper", l1: "Compra", l2: "Lenta", l3: "Esperar" },
    { solution: "Auriculares", l1: "Música", l2: "Cables", l3: "Uno se pierde" },
    { solution: "Notificación", l1: "Móvil", l2: "Sonido", l3: "Atención" },
    { solution: "Contraseña", l1: "Seguridad", l2: "Difícil", l3: "Se olvida" },

    { solution: "Bolígrafo", l1: "Escribir", l2: "Clase", l3: "Desaparece" },
    { solution: "Agenda", l1: "Organización", l2: "Apuntar", l3: "Plan" },
    { solution: "Espera", l1: "Tiempo", l2: "Aburrimiento", l3: "Paciencia" },
    { solution: "Puerta", l1: "Objeto", l2: "Abrir o cerrar", l3: "Paso" },
    { solution: "Ventana", l1: "Casa", l2: "Luz", l3: "Aire" },
    { solution: "Vecino", l1: "Persona", l2: "Cerca", l3: "Ruido" },
    { solution: "Tráfico", l1: "Coches", l2: "Ciudad", l3: "Estrés" },
    { solution: "Horario", l1: "Tiempo", l2: "Rutina", l3: "Orden" },
    { solution: "Mensaje leído", l1: "Chat", l2: "Silencio", l3: "Duda" },
    { solution: "Plan", l1: "Idea", l2: "Personas", l3: "Organizar" },

    { solution: "Llamada perdida", l1: "Móvil", l2: "Pantalla", l3: "Intriga" },
    { solution: "Reunión", l1: "Personas", l2: "Hablar", l3: "Tiempo" },
    { solution: "Fila del baño", l1: "Lugar", l2: "Prisa", l3: "Esperar" },
    { solution: "Cambio suelto", l1: "Dinero", l2: "Bolsillo", l3: "Ruido" },
    { solution: "Ticket", l1: "Papel", l2: "Compra", l3: "Se pierde" },
    { solution: "Mapa", l1: "Ubicación", l2: "Buscar", l3: "Orientarse" },
    { solution: "Silencio", l1: "Ambiente", l2: "Calma", l3: "Raro" },
    { solution: "Reloj", l1: "Tiempo", l2: "Mirar", l3: "Tarde" },
    { solution: "Esperar respuesta", l1: "Mensaje", l2: "Tiempo", l3: "Incertidumbre" },
    { solution: "Plan cancelado", l1: "Aviso", l2: "Última hora", l3: "Fastidio" },

    // ===== DEPORTES (10) =====
    { solution: "Fútbol", l1: "Deporte", l2: "Balón", l3: "Equipo" },
    { solution: "Baloncesto", l1: "Canasta", l2: "Equipo", l3: "Puntos" },
    { solution: "Tenis", l1: "Raqueta", l2: "Individual", l3: "Red" },
    { solution: "Natación", l1: "Agua", l2: "Piscina", l3: "Resistencia" },
    { solution: "Ciclismo", l1: "Bicicleta", l2: "Ruta", l3: "Piernas" },
    { solution: "Boxeo", l1: "Combate", l2: "Guantes", l3: "Ring" },
    { solution: "Running", l1: "Correr", l2: "Zapatillas", l3: "Resistencia" },
    { solution: "Pádel", l1: "Parejas", l2: "Pared", l3: "Raqueta" },
    { solution: "Crossfit", l1: "Alta intensidad", l2: "Circuito", l3: "Cansancio" },
    { solution: "Surf", l1: "Mar", l2: "Tabla", l3: "Olas" },

    // ===== FAMOSOS (10) =====
    { solution: "Messi", l1: "Fútbol", l2: "Argentino", l3: "Balón de oro" },
    { solution: "Cristiano Ronaldo", l1: "Fútbol", l2: "Portugués", l3: "Goles" },
    { solution: "Ibai", l1: "Streamer", l2: "Eventos", l3: "Twitch" },
    { solution: "Bad Bunny", l1: "Cantante", l2: "Reguetón", l3: "Puerto Rico" },
    { solution: "Aitana", l1: "Cantante", l2: "Pop", l3: "España" },
    { solution: "Shakira", l1: "Cantante", l2: "Latina", l3: "Baile" },
    { solution: "TheGrefg", l1: "Youtuber", l2: "Gaming", l3: "Directos" },
    { solution: "Karol G", l1: "Música", l2: "Colombia", l3: "Éxitos" },
    { solution: "Piqué", l1: "Exfutbolista", l2: "Empresa", l3: "Kings League" },
    { solution: "Duki", l1: "Trap", l2: "Argentina", l3: "Conciertos" },

    // ===== GIMNASIO (10) =====
    { solution: "Press banca", l1: "Pecho", l2: "Barra", l3: "Fuerza" },
    { solution: "Sentadilla", l1: "Piernas", l2: "Peso", l3: "Ejercicio" },
    { solution: "Peso muerto", l1: "Espalda", l2: "Barra", l3: "Técnica" },
    { solution: "Mancuernas", l1: "Material", l2: "Brazos", l3: "Pesos" },
    { solution: "Proteína", l1: "Suplemento", l2: "Batido", l3: "Recuperación" },
    { solution: "Series", l1: "Entreno", l2: "Repeticiones", l3: "Descanso" },
    { solution: "Cardio", l1: "Resistencia", l2: "Correr", l3: "Sudor" },
    { solution: "Monitor", l1: "Gimnasio", l2: "Ayuda", l3: "Rutina" },
    { solution: "Agujetas", l1: "Dolor", l2: "Después", l3: "Entreno" },
    { solution: "Máquinas", l1: "Gimnasio", l2: "Pesos", l3: "Rutina" },

    // ===== TEMÁTICA LIBRE: VIDA COTIDIANA (10) =====
    { solution: "Móvil", l1: "Tecnología", l2: "Pantalla", l3: "Diario" },
    { solution: "Coche", l1: "Transporte", l2: "Conducir", l3: "Viaje" },
    { solution: "Trabajo", l1: "Rutina", l2: "Horario", l3: "Responsabilidad" },
    { solution: "Fiesta", l1: "Noche", l2: "Amigos", l3: "Música" },
    { solution: "Vacaciones", l1: "Descanso", l2: "Viaje", l3: "Tiempo libre" },
    { solution: "Casa", l1: "Lugar", l2: "Descanso", l3: "Hogar" },
    { solution: "Cena", l1: "Comida", l2: "Noche", l3: "Mesa" },
    { solution: "Mensaje", l1: "Comunicación", l2: "Móvil", l3: "Texto" },
    { solution: "Plan", l1: "Idea", l2: "Personas", l3: "Organizar" },
    { solution: "Fin de semana", l1: "Tiempo libre", l2: "Descanso", l3: "Esperado" }
];